main: economy.main.Economy
name: Economy
version: "0.1"
author: Der_Zauberer
api-version: 1.12

commands:
  money:
    description: Open the bank menu
    usage: /<command>
    permission: economy.command.money
    aliases: [bank]
  profile:
    description: Open the bank menu
    usage: /<command>
    permission: economy.command.profile

permissions:
  economy.command.money:
    description: Open the bank menu
    default: true
  economy.command.profile:
    description: Open the profile menu
    default: true
  economy.command.profile.inspect:
    description: Open the profile menu of an other player
    default: op